language: csharp
mono: none

matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.1
      install:
        - dotnet restore
        - |
          dotnet user-secrets set "Client:ClientId" ${CTP_CLIENT_ID} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "Client:ClientSecret" ${CTP_CLIENT_SECRET} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "Client:Scope" ${CTP_CLIENT_SCOPE} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "Client:ProjectKey" ${CTP_PROJECTKEY} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClient:ClientId" ${CTP_CLIENT_ID} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClient:ClientSecret" ${CTP_CLIENT_SECRET} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClient:Scope" ${CTP_CLIENT_SCOPE} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClient:ProjectKey" ${CTP_PROJECTKEY} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithSmallerScope:ClientId" ${CTP_CLIENT_ID} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithSmallerScope:ClientSecret" ${CTP_CLIENT_SECRET} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithSmallerScope:Scope" ${CTP_CLIENT_SCOPE} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithSmallerScope:ProjectKey" ${CTP_PROJECTKEY} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithAnonymousScope:ClientId" ${CTP_CLIENT_ID} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithAnonymousScope:ClientSecret" ${CTP_CLIENT_SECRET} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithAnonymousScope:Scope" ${CTP_CLIENT_SCOPE} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
          dotnet user-secrets set "TokenClientWithAnonymousScope:ProjectKey" ${CTP_PROJECTKEY} --project commercetools.Sdk.HttpApi.IntegrationTests > /dev/null 2>&1
    - os: windows
      filter_secrets: false
      install:
        - choco install dotnetcore-sdk --version 2.1.603
        - dotnet restore
        - powershell -c 'dotnet user-secrets set "Client:ClientId" $env:CTP_CLIENT_ID --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "Client:ClientSecret" $env:CTP_CLIENT_SECRET --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "Client:Scope" $env:CTP_CLIENT_SCOPE --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "Client:ProjectKey" $env:CTP_PROJECTKEY --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClient:ClientId" $env:CTP_CLIENT_ID --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClient:ClientSecret" $env:CTP_CLIENT_SECRET --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClient:Scope" $env:CTP_CLIENT_SCOPE --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClient:ProjectKey" $env:CTP_PROJECTKEY --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithSmallerScope:ClientId" $env:CTP_CLIENT_ID --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithSmallerScope:ClientSecret" $env:CTP_CLIENT_SECRET --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithSmallerScope:Scope" $env:CTP_CLIENT_SCOPE --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithSmallerScope:ProjectKey" $env:CTP_PROJECTKEY --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithAnonymousScope:ClientId" $env:CTP_CLIENT_ID --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithAnonymousScope:ClientSecret" $env:CTP_CLIENT_SECRET --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithAnonymousScope:Scope" $env:CTP_CLIENT_SCOPE --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'
        - powershell -c 'dotnet user-secrets set "TokenClientWithAnonymousScope:ProjectKey" $env:CTP_PROJECTKEY --project commercetools.Sdk.HttpApi.IntegrationTests >$null 2>&1'

before_install:
 - cd commercetools.Sdk

script:
  - dotnet build -c Release
  - dotnet test Tests --no-build -c Release
#  - dotnet test commercetools.Sdk.HttpApi.IntegrationTests --no-build -c Release
